### ISSUE TITLE
Consider unexporting the Systems type

### ISSUE THREAD

**Issue by mewmew** [EngoEngine/ecs#16]
To minimize the public API to the core concepts of ECS, I propose we unexport the [Systems](https://github.com/EngoEngine/ecs/blob/a9bcc97b06e1906050c63a0e1f2695328381dfe0/system.go#L25) type. It may be considered an internal detail of the `ecs` package, and should users of `ecs` want to use a similar priority queue outside of `World`, the implementation of the `sort.Sort` interface is trivial.

The `Systems` type is only used by the private `systems` field of the `World` structure, and  the `Systems` method on `World` returns `[]System` rather than `Systems`. Therefore we may easily unexport it, without breaking too many users. And, obviously the time to make changes to core packages like `ecs` is now since #13 was just merged, and all users have to update their code anyways.

From [world.go](https://github.com/EngoEngine/ecs/blob/a9bcc97b06e1906050c63a0e1f2695328381dfe0/world.go#L10)
```go
type World struct {
	systems Systems
}

// Systems returns a list of Systems
func (w *World) Systems() []System {
	return w.systems
}
```

**Comment by EtienneBruines** [comment]
SGTM.

**Comment by mewmew** [comment]
> SGTM.

Would you mind me preparing a pull-request?
