### ISSUE TITLE
example that uses ecs.BasicFace

### ISSUE THREAD

**Issue by gravestench** [EngoEngine/ecs#44]
maybe just me, but I am not able to use `ecs.BasicFace` to extend an interface.

**Comment by gravestench** [comment]
I think it has to do with `BasicFace` being defined inside one of your tests. Goland doesn't like it, will not auto-complete, not sure if it affects compiling but I just redefined the interface in my code.

**Comment by Noofbiz** [comment]
The issue at the time was that BasicFace is defined in 'EngoEngine/engo/common' already, but I needed it for that test, so I redefined it in the test only to test it without importing all of engo and common lol
