### ISSUE TITLE
ecs.BasicFace does not exist

### ISSUE THREAD

**Issue by chrispytoes** [EngoEngine/ecs#45]
I'm going through the "Automatically add entities to systems" section in the readme, and I'm stuck at this part in the example:
```
type Myable interface {
    ecs.BasicFace
    AFace
}
```
I do not have the `ecs.BasicFace` interface, and therefore cannot move on to the next step which calls `obj.GetBasicEntity()`. Has this been changed and the readme not updated?

**Comment by Noofbiz** [comment]
You’re right, I think a BasicFace in ecs itself would be a nice addition. The one I use is `common.BasicFace’ in engo/common but I think there should be one here. The ecs.BasicFace was created in the test files so I didn’t have to import all of engo just to run tests, and then I just copy/pasted the tutorial from the tests. Sorry for the inconvenience

**Comment by chrispytoes** [comment]
@Noofbiz Ah, that would make sense then. I only need the ecs package without engo. I did do a search for it in the source and I found the implementation of it in the test so I just copied that into my code.

**Comment by Noofbiz** [comment]
I added it to the library itself; once I add go.mod and GitHub actions I'll release a new version you can update to ^_^
